/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entity.Entitas;
import Factory.FactoryTransaksi;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import Interface.InterfaceTransaksi;
public class FormTransaksiPembayaran extends javax.swing.JFrame {
   private DefaultTableModel dtdtmpt;
   private String[] tabelHeader;
   private InterfaceTransaksi ditempatDAO;
   private Entitas trx;
   public String idpelanggan, nama, kdmenu, namamenu;
   public int total1, total2, harga, baris, subTotal, total;
   
   private String tanggal(){
       DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
       Date d = new Date();
       return df.format(d);
   }
   
    private void aturButton (boolean status){
        btnAdd.setEnabled(status);
        btnSave.setEnabled(!status);
        if(status == true){
            btnExit.setText("Keluar");
        }else{
            btnExit.setText("Batal");
        }
    }
    
    private void aturTeks (){
        txtUangBayar1.setEditable(false);
        txtTanggal.setEditable(false);
        txtKodeMenu.setEditable(false);
        txtNamaMenu.setEditable(false);
        txtNoMeja.setEditable(false);
        txtHargaMenu.setEditable(false);
        txtJumlah.setEditable(false);
        txtIdPelanggan.setEditable(false);
        txtNamaPemesan.setEditable(false);
        txtTanggal.setText(tanggal());
        txtTotalDitempat.setEditable(false);
        txtKembalian.setEditable(false);
    }
    
    private void teksKosong(){
        txtIdPelanggan.setText("");
        txtNamaPemesan.setText("");
        txtKodeMenu.setText("");
        txtNamaMenu.setText("");
        txtHargaMenu.setText("");
        txtNoMeja.setText("");
        txtJumlah.setText("");
    }
    
    private void aturTable(){
        tabelHeader = new String[]{"KODE MENU", "NO MEJA", 
            "NAMA MENU", "HARGA MENU","JUMLAH"};
        dtdtmpt = new DefaultTableModel(null, tabelHeader);
        TblDitempat.setModel(dtdtmpt);
        }
    
    String nama_karyawan = Entity.Entitas.getKaryawan();
    String id_karyawan = Entity.Entitas.getIdkaryawan();
    
        public FormTransaksiPembayaran() {
        initComponents();
        txtNamaKaryawan.setText(nama_karyawan);
        txtIDKaryawan.setText(id_karyawan);
        ditempatDAO = FactoryTransaksi.getDitempatDAO();
        setLocationRelativeTo(this);
        txtIDKaryawan.setEditable(false);
        txtNamaKaryawan.setEditable(false);
        txtNota.setEditable(false);
        aturTable();    
        aturButton(true);
        btnAdd.requestFocus();
        aturTeks();
         TblDitempat.getSelectionModel().addListSelectionListener(new 
        ListSelectionListener () {
                    
    public void valueChanged(ListSelectionEvent e) {
        baris = TblDitempat.getSelectedRow();
        if(baris >= 0){
            txtHargaMenu.setText(dtdtmpt.getValueAt(baris, 3).toString());
            txtJumlah.setText(dtdtmpt.getValueAt(baris, 4).toString());
            }
        
         }
        }); 
    }
    
    /*public FormTransaksiDitempat(String idpelanggan, String nama, String kdmenu, String namamenu,
            int harga){
        initComponents();
        setLocationRelativeTo(this);
        this.idpelanggan = idpelanggan;
        this.nama = nama;
        this.kdmenu = kdmenu;
        this.namamenu = namamenu;
        this.harga = harga;
        txtIdPelanggan.setText(idpelanggan);
        txtNamaPemesan.setText(nama);
        txtKodeMenu.setText(kdmenu);
        txtNamaMenu.setText(namamenu);
        txtHargaMenu.setText(String.valueOf(harga));
        txtNota.setEditable(false);
        aturTable();
        aturButton(true);
        aturTeks();
    }*/
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUangBayar1 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTotalDitempat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        txtProses1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtKodeMenu = new javax.swing.JTextField();
        txtNamaMenu = new javax.swing.JTextField();
        txtHargaMenu = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNamaPemesan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdPelanggan = new javax.swing.JTextField();
        btnCariPelanggan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        btnCariMenu = new javax.swing.JButton();
        txtNoMeja = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDitempat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIDKaryawan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNamaKaryawan = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bayar (Rp)");

        txtUangBayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangBayar1ActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total Pembayaran (Rp)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Kembalian");

        txtProses1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProses1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bayarr.png"))); // NOI18N
        txtProses1.setText("Proses");
        txtProses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProses1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Kode Menu");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("No Meja");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nama Menu");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Harga Menu");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Jumlah");

        txtKodeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMenuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nama Pemesan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID Pelanggan");

        btnCariPelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCariPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cari.png"))); // NOI18N
        btnCariPelanggan.setText("Cari");
        btnCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPelangganActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nota");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal");

        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("INPUT DATA PESANAN");

        btnCariMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCariMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cari.png"))); // NOI18N
        btnCariMenu.setText("Cari");
        btnCariMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel14))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaMenu))
                                .addGap(2, 2, 2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNoMeja, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCariMenu))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(txtNamaPemesan))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCariPelanggan))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(93, 93, 93)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKodeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCariMenu)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHargaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        TblDitempat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TblDitempat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Menu", "No Meja", "Nama Menu", "Harga Menu", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(TblDitempat);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI MENU");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Karyawan");

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUangBayar1)
                            .addComponent(txtKembalian, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalDitempat)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProses1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTotalDitempat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtUangBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)
                                .addContainerGap(22, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnSave)
                            .addComponent(txtProses1)
                            .addComponent(btnBatal))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    btnSave.setEnabled(true);
    btnAdd.setEnabled(false);
    ditempatDAO=FactoryTransaksi.getDitempatDAO();
    setLocationRelativeTo(this);
    txtUangBayar1.setEditable(true);
    txtTanggal.setText(tanggal());
    txtNota.setText(ditempatDAO.kodeBaru());
    txtNota.setEditable(false);
    txtTanggal.setEditable(false);
    txtIdPelanggan.setEditable(false);
    txtNamaPemesan.setEditable(false);
    txtKodeMenu.setEditable(false);
    txtNoMeja.setEditable(true);
    txtNamaMenu.setEditable(false);
    txtHargaMenu.setEditable(false);
    txtJumlah.setEditable(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    if (btnExit.getText().equals("Keluar")){
        FormMenuUtamaKaryawan form = new FormMenuUtamaKaryawan();
     form.setVisible(true);
            dispose();
    }else {
        aturButton(true);
        teksKosong();
        txtTotalDitempat.setText("");
        txtUangBayar1.setText("");
        txtKembalian.setText("");
        aturTable();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void txtProses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProses1ActionPerformed

    char[] data = txtNoMeja.getText().toCharArray();
    char[] data1 = txtJumlah.getText().toCharArray();
    boolean valid = true;
    boolean valid1 = true;
    for (char c : data) {
    if (!Character.isDigit(c)) {
        valid = false;
        break;
     }
    }    
      for (char c : data1) {
    if (!Character.isDigit(c)) {
        valid1 = false;
        break;
     }
    }  
    if(txtNamaMenu.getText().equals("") || txtHargaMenu.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Pilih Menu Yang Ingin Dipesan !");
    }else if(txtNoMeja.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Nomor Meja Wajib Diisi !");   
    txtNoMeja.requestFocus();
    }else if(valid==false){
    JOptionPane.showMessageDialog(null, "Nomor Meja Harus Diisi Dengan Angka !");   
    txtNoMeja.requestFocus();
    }else if(txtJumlah.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Masukan Jumlah Menu Yang Ingin Dipesan !");   
    txtJumlah.requestFocus();
    }else if(valid1==false){
    JOptionPane.showMessageDialog(null, "Jumlah Harus Diisi Dengan Angka !");   
    txtJumlah.requestFocus();
    }
    else {
    subTotal=0;
    subTotal = Integer.parseInt(txtHargaMenu.getText())*
            Integer.parseInt(txtJumlah.getText());
    dtdtmpt.addRow(new Object[]{txtKodeMenu.getText(), txtNoMeja.getText(), 
        txtNamaMenu.getText(),txtHargaMenu.getText(), txtJumlah.getText()});
    total2+=subTotal;
    txtTotalDitempat.setText(String.valueOf(total2));   
    txtJumlah.setText("");
    txtKodeMenu.setEditable(false);
    txtNamaMenu.setEditable(false);
    txtHargaMenu.setEditable(false);
    txtJumlah.setEditable(true);
    txtNoMeja.setEditable(false);
    txtNota.setEditable(false);
    txtTanggal.setEditable(false);
    txtIdPelanggan.setEditable(false);
    txtNamaPemesan.setEditable(false);
       JOptionPane.showMessageDialog(null, "Menu Yang Dipilih Berhasil Diproses !"); 
    }
    
    }//GEN-LAST:event_txtProses1ActionPerformed

    private void txtKodeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMenuActionPerformed

    private void btnCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPelangganActionPerformed
    boolean closable = true;
    FormCariPelanggan cari = new FormCariPelanggan(null, closable);
    cari.trx = this;
    cari.setVisible(true);
    cari.setResizable(true);
    txtIdPelanggan.setText(idpelanggan);
    txtNamaPemesan.setText(nama);
    
    }//GEN-LAST:event_btnCariPelangganActionPerformed

    private void txtUangBayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangBayar1ActionPerformed
   char[] data = txtUangBayar1.getText().toCharArray();
    boolean valid = true;
    for (char c : data) {
    if (!Character.isDigit(c)) {
        valid = false;
        break;
     }
    }    
        
   if(txtUangBayar1.getText().equals("")){
  JOptionPane.showMessageDialog(null, "Masukan Jumlah Uang Pembayaran !");   
   txtUangBayar1.requestFocus();
   }else if(valid==false){
  JOptionPane.showMessageDialog(null, "Nominal Pembayaran Harus Diisi Dengan Angka !");  
  txtUangBayar1.requestFocus();
   }
   else{
    int kembali;
    kembali = Integer.parseInt(txtUangBayar1.getText())
            -Integer.parseInt(txtTotalDitempat.getText());
    txtKembalian.setText(String.valueOf(kembali));
    if(kembali<0){
        JOptionPane.showMessageDialog(null, "Maaf Uang Pembayaran Kurang", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        txtUangBayar1.requestFocus();     
    }else{
        JOptionPane.showMessageDialog(null, "Uang Kembalian Rp"+kembali);
        teksKosong();
        txtTotalDitempat.setText("");
        txtUangBayar1.setText("");
        txtKembalian.setText("");
        aturButton(true);
        btnSaveActionPerformed(evt);
    }
   }
    }//GEN-LAST:event_txtUangBayar1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    int i;
    trx = new Entitas();
    trx.setNonota(txtNota.getText());
    trx.setId_karyawan(txtIDKaryawan.getText());
    trx.setId_pelanggan(idpelanggan);
    trx.setTgl(txtTanggal.getText());
    ditempatDAO.insertDitempat(trx);
    baris = TblDitempat.getRowCount();
    JOptionPane.showMessageDialog(null, "Data Trasaksi Menu Berhasil Disimpan");
    for(i=0;i<baris;i++){
        trx.setKd_menu(dtdtmpt.getValueAt(i, 0).toString());
        trx.setMeja(dtdtmpt.getValueAt(i,1).toString());
        trx.setHarga_menu(Integer.parseInt(dtdtmpt.getValueAt(i, 3).toString()));
        trx.setJml(Integer.parseInt(dtdtmpt.getValueAt(i, 4).toString()));
        ditempatDAO.insertDetailDitempat(trx);}
        aturButton(true);
        teksKosong();
        btnSave.setEnabled(false);
        btnAdd.setEnabled(true);
        txtTotalDitempat.setText("");
        txtUangBayar1.setText("");
        txtKembalian.setText("");
        aturTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCariMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMenuActionPerformed
       boolean closable = true;
    FormCariMenu cari = new FormCariMenu(null, closable);
    cari.trx = this;
    cari.setVisible(true);
    cari.setResizable(true);
    txtKodeMenu.setText(kdmenu);
    txtNamaMenu.setText(namamenu);
    txtHargaMenu.setText(String.valueOf(harga));
    }//GEN-LAST:event_btnCariMenuActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
    int tampung=0, tmp=0;
    if(TblDitempat.getSelectedRow() >= 0){
    dtdtmpt.removeRow(TblDitempat.getSelectedRow());
    tmp=Integer.parseInt(txtHargaMenu.getText())*Integer.parseInt(txtJumlah.getText());
    tampung=Integer.parseInt(txtTotalDitempat.getText())-tmp;
    total2=tampung;
    txtTotalDitempat.setText(String.valueOf(tampung));
    JOptionPane.showMessageDialog(null, "Menu Yang Dipilih Berhasil Dibatalkan !");   
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksiPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblDitempat;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariMenu;
    private javax.swing.JButton btnCariPelanggan;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHargaMenu;
    private javax.swing.JTextField txtIDKaryawan;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKodeMenu;
    private javax.swing.JTextField txtNamaKaryawan;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtNamaPemesan;
    private javax.swing.JTextField txtNoMeja;
    private javax.swing.JTextField txtNota;
    private javax.swing.JButton txtProses1;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotalDitempat;
    private javax.swing.JTextField txtUangBayar1;
    // End of variables declaration//GEN-END:variables
}
